export const bedrooms = [
  {
    imgSrc: "bedroom/bedroom01.jpeg",
    imgAlt: "bedroom01",
    title: "Broma Bed Side Table",
    newPrice: "58.0",
    btnName: "Add to Cart",
    link: "/product/broma-bed-side-table",
  },
  {
    imgSrc: "bedroom/bedroom02.jpeg",
    imgAlt: "bedroom02",
    title: "Bachelor Bed",
    newPrice: "75.0",
    btnName: "Add to Cart",
    link: "/product/bachelor-bed",
  },
  {
    imgSrc: "bedroom/bedroom03.jpeg",
    imgAlt: "bedroom03",
    title: "Bedroom Exclusive Mattress",
    discount: "-16%",
    oldPrice: "238.0",
    newPrice: "199.0",
    btnName: "Select Options",
    link: "/product/bedroom-exclusive-mattress",
  },
  {
    imgSrc: "bedroom/bedroom04.jpeg",
    imgAlt: "bedroom04",
    title: "Minimalist Mid-Century Modern Style Bed",
    newPrice: "159.0",
    btnName: "Select Options",
    link: "/product/minimalist-mid-century-modern-style-bed",
  },
  {
    imgSrc: "bedroom/bedroom05.jpeg",
    imgAlt: "bedroom05",
    title: "Josefa Queen Size Bed with Storage in Natural Teak Wood Finish",
    newPrice: "199.0",
    btnName: "Add to Cart",
    link: "/product/josefa-queen-size-bed-with-storage-in-natural-teak-wood-finish",
  },
];
export const Dinings = [
  {
    thumbSrc: "tabOne/var5.jpeg",
    thumbAlt: "var5",
    typ: "sale",
    discount: "-16%",
    link: "/product/round-dining-table-without-chair",
    name: "Round Dining Table without chair",
    oldPrice: "239.0",
    newPrice: "201.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var4.jpeg",
    thumbAlt: "var4",
    link: "/product/twist-dining-table",
    name: "Twist Dining Table",
    newPrice: "288.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var1.jpeg",
    thumbAlt: "var1",
    hovthumbSrc: "tabOne/var1c.jpeg",
    hovthumbAlt: "var1c",
    discount: "-42%",
    link: "/product/variable-product",
    name: "Variable Product",
    oldPrice: "119.0",
    newPrice: "69.0",
    btnName: "Select Options",
  },
];
export const Lounges = [
  {
    thumbSrc: "tabOne/var7.jpeg",
    thumbAlt: "var7",
    link: "/product/high-back-lounge-office-chairs",
    name: "High back lounge office chairs",
    newPrice: "499.0",
    btnName: "Add to Cart",
  },
];
export const OfficeChairs = [
  {
    thumbSrc: "tabOne/var12.jpeg",
    thumbAlt: "var12",
    typ: "sale",
    discount: "-6%",
    link: "/product/developer-chair",
    name: "Developer Chair",
    oldPrice: "211.0",
    newPrice: "199.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var70.jpeg",
    thumbAlt: "var70var70",
    link: "/product/optima-high-back-chair",
    name: "Grey Scandinavian Chair",
    newPrice: "68.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var13.jpeg",
    thumbAlt: "var13",
    hovthumbSrc: "tabOne/var13c.jpeg",
    hovthumbAlt: "var13c",
    link: "/product/optima-high-back-chair",
    name: "Optima High Back Chair",
    newPrice: "211.0",
    btnName: "Select Options",
  },
];
export const HospitalBeds = [
  {
    thumbSrc: "tabOne/var11.jpeg",
    thumbAlt: "var11",
    typ: "sale",
    discount: "-14%",
    link: "/product/simple-hospital-manual-patient-bed",
    name: "Simple Hospital Manual Patient Bed",
    oldPrice: "389.0",
    newPrice: "333.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var14.jpeg",
    thumbAlt: "var14",
    link: "/product/hospital-bed-tranquil",
    name: "Hospital bed Tranquil",
    newPrice: "666.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var10.jpeg",
    thumbAlt: "var10",
    typ: "sale",
    discount: "-3%",
    link: "/product/surgery-bed",
    name: "Surgery Bed",
    oldPrice: "899.0",
    newPrice: "869.0",
    btnName: "Add to Cart",
  },
];
export const HospitalUtilitys = [
  {
    thumbSrc: "tabOne/var80.jpeg",
    thumbAlt: "var80",
    link: "product/wheel-chair",
    name: "Wheelchair",
    newPrice: "159.0",
    btnName: "Add to Cart",
  },

  {
    thumbSrc: "tabOne/var9.jpeg",
    thumbAlt: "var9",
    link: "product/rollator-walker-lightweight-4-wheels-folding",
    name: "Rollator walker lightweight 4 wheels folding",
    newPrice: "119.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var6.jpeg",
    thumbAlt: "var6",
    typ: "sale",
    discount: "-13%",
    link: "/product/hospital-reception-table",
    name: "Hospital Reception Table",
    oldPrice: "399.0",
    newPrice: "349.0",
    btnName: "Add to Cart",
  },
];
