export const ItemsTow = [
  {
    thumbSrc: "tabOne/var1.jpeg",
    thumbAlt: "var1",
    hovthumbSrc: "tabOne/var1c.jpeg",
    hovthumbAlt: "var1c",
    typ: "sale",
    discount: "-42%",
    link: "/product/variable-product",
    name: "Variable Product",
    oldPrice: "119.0",
    newPrice: "69.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var2.jpeg",
    thumbAlt: "var2",
    link: "product/josefa-queen-size-bed-with-storage-in-natural-teak-wood-finish",
    name: "Josefa Queen Size Bed with Storage in Natural Teak Wood Finish",
    newPrice: "199.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var5.jpeg",
    thumbAlt: "var5",
    typ: "sale",
    discount: "-16%",
    link: "product/round-dining-table-without-chair",
    name: "Round Dining Table without chair",
    oldPrice: "239.0",
    newPrice: "201.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var9.jpeg",
    thumbAlt: "var9",
    typ: "sale",
    discount: "-16%",
    link: "product/rollator-walker-lightweight-4-wheels-folding",
    name: "Rollator walker lightweight 4 wheels folding",
    oldPrice: "239.0",
    newPrice: "201.0",
    btnName: "Add to Cart",
  },
];
