export const ItemsThree = [
  {
    thumbSrc: "tabOne/var1.jpeg",
    thumbAlt: "var1",
    hovthumbSrc: "tabOne/var1c.jpeg",
    hovthumbAlt: "var1c",
    typ: "sale",
    discount: "-42%",
    link: "/product/variable-product",
    name: "Variable Product",
    oldPrice: "119.0",
    newPrice: "69.0",
    btnName: "Select Options",
  },
  {
    thumbSrc: "tabOne/var5.jpeg",
    thumbAlt: "var5",
    typ: "sale",
    discount: "-16%",
    link: "/product/round-dining-table-without-chair",
    name: "Round Dining Table without chair",
    oldPrice: "239.0",
    newPrice: "201.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var6.jpeg",
    thumbAlt: "var6",
    typ: "sale",
    discount: "-13%",
    link: "/product/hospital-reception-table",
    name: "Hospital Reception Table",
    oldPrice: "399.0",
    newPrice: "349.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var8.jpeg",
    thumbAlt: "var8",
    typ: "sale",
    discount: "-16%",
    link: "/product/bedroom-exclusive-mattress",
    name: "Bedroom Exclusive Mattress",
    oldPrice: "238.0",
    newPrice: "199.0",
    btnName: "Select Options",
  },
  {
    thumbSrc: "tabOne/var10.jpeg",
    thumbAlt: "var10",
    typ: "sale",
    discount: "-3%",
    link: "/product/surgery-bed",
    name: "Surgery Bed",
    oldPrice: "899.0",
    newPrice: "869.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var11.jpeg",
    thumbAlt: "var11",
    typ: "sale",
    discount: "-14%",
    link: "/product/simple-hospital-manual-patient-bed",
    name: "Simple Hospital Manual Patient Bed",
    oldPrice: "389.0",
    newPrice: "333.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var12.jpeg",
    thumbAlt: "var12",
    typ: "sale",
    discount: "-6%",
    link: "/product/developer-chair",
    name: "Developer Chair",
    oldPrice: "211.0",
    newPrice: "199.0",
    btnName: "Add to Cart",
  },
];
