export const ItemsOne = [
  {
    thumbSrc: "tabOne/var1.jpeg",
    thumbAlt: "var1",
    hovthumbSrc: "tabOne/var1c.jpeg",
    hovthumbAlt: "var1c",
    discount: "-42%",
    link: "/product/variable-product",
    name: "Variable Product",
    oldPrice: "119.0",
    newPrice: "69.0",
    btnName: "Select Options",
  },
  {
    thumbSrc: "tabOne/var2.jpeg",
    thumbAlt: "var2",
    link: "/product/josefa-queen-size-bed-with-storage-in-natural-teak-wood-finish",
    name: "Josefa Queen Size Bed with Storage in Natural Teak Wood Finish",
    newPrice: "199.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var3.jpeg",
    thumbAlt: "var3",
    link: "/product/minimalist-mid-century-modern-style-bed",
    name: "Minimalist Mid-Century Modern Style Bed",
    newPrice: "159.0",
    btnName: "Select Options",
  },
  {
    thumbSrc: "tabOne/var4.jpeg",
    thumbAlt: "var4",
    link: "/product/twist-dining-table",
    name: "Twist Dining Table",
    newPrice: "288.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var5.jpeg",
    thumbAlt: "var5",
    typ: "sale",
    discount: "-16%",
    link: "/product/round-dining-table-without-chair",
    name: "Round Dining Table without chair",
    oldPrice: "239.0",
    newPrice: "201.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var6.jpeg",
    thumbAlt: "var6",
    typ: "sale",
    discount: "-13%",
    link: "/product/hospital-reception-table",
    name: "Hospital Reception Table",
    oldPrice: "399.0",
    newPrice: "349.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var7.jpeg",
    thumbAlt: "var7",
    link: "/product/high-back-lounge-office-chairs",
    name: "High back lounge office chairs",
    newPrice: "499.0",
    btnName: "Add to Cart",
  },
  {
    thumbSrc: "tabOne/var8.jpeg",
    thumbAlt: "var8",
    typ: "sale",
    discount: "-16%",
    link: "/product/bedroom-exclusive-mattress",
    name: "Bedroom Exclusive Mattress",
    oldPrice: "238.0",
    newPrice: "199.0",
    btnName: "Select Options",
  },
];
