import Head from "next/head";
import styles from "../styles/Home.module.css";
import FirstHome from "./FirstHome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Furns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/front_row.ico" />
      </Head>
      <FirstHome />
    </>
  );
}
